services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.secrets/db-dev.env
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.secrets/app-dev.env
    volumes:
      - .:/thalia
    ports:
      - "3000:3000"
    depends_on:
      - db
